
spring:
#  jersey:
#    application-path: /api
  profiles:
    active: dev
  application:
    name: ucenter

server:
  port: 9080
  #context-path: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true

